export const grupos = [
  {
    nombre: "GRUPO 1",
    miembros: [
      "Barrera Alvaro",
      "Godoy Juan",
      "Armirola Libia",
      "Barrera Camila",
      "Barrera Mery",
      "Barrera Michel",
      "Conde Keily",
      "Duran Ana",
      "Florez Ruth",
      "Godoy Elizabeth",
      "Hernández Harold",
      "Luna Jesús",
      "Luna Silvia",
      "Martinez Enma",
      "Mendoza Dora",
      "Mendoza Ramiro",
      "Melo Reinaldo",
      "Melo Yolando",
      "Serrano Samuel",
      "Suárez Celeste",
    ],
  },
  {
    nombre: "GRUPO 2",
    miembros: [
      "Delgado Adrian",
      "Pérez Alexander",
      "Barreto Joel",
      "Barreto Rosmery",
      "Bolaños Andi",
      "Cielo Doris",
      "Delgado Deisy",
      "Delgado Yolanda",
      "Garzón Paulina",
      "Gimenez Jenny",
      "Hernández Magaly",
      "Jaramillo Blanca",
      "Ortiz Jenny",
      "Ortiz Jonatan",
      "Perez Karen",
      "Quintero Sol",
      "Roso Daniela",
      "Suárez Rosa",
      "Velázquez Concepcion",
      "Velázquez Samuel",
    ],
  },
  {
    nombre: "GRUPO 3",
    miembros: [
      "González Moises",
      "Sabas Mauricio",
      "Correa Pedro",
      "Correa Sara",
      "Gomes Antonio",
      "Gomez Clara",
      "Gomez Nidia",
      "González Yoangélica",
      "López Antonio",
      "López Aura",
      "Peña Olida",
      "Ramos Yendry",
      "Rangel José",
      "Rangel Piedad",
      "Rivera Ciro",
      "Rivera Zulay",
      "Romero José",
      "Romero Syned",
      "Sabas Sandra",
      "Valdez Alirio",
    ],
  },
  {
    nombre: "GRUPO 4",
    miembros: [
      "Menjura Juan",
      "Graterol Jeremías",
      "Araque Greimar",
      "Araque Maria",
      "García Patricia",
      "Guarín Jessica",
      "Gutierrez Berta",
      "Hernández Edgar",
      "Hernández Martha",
      "Menjura Edilma",
      "Rivera Alexander",
      "Rivera Maria",
      "Rojas Angel",
      "Rojas Richard",
      "Rojas Thais",
      "Rojas Yeison",
      "Sánchez Doris",
      "Sánchez Estefany",
      "Suárez Gladys",
      "Zerpa Martín",
    ],
  },
  {
    nombre: "GRUPO 5",
    miembros: [
      "Flores Juan",
      "Murillo Loncio",
      "Aldana Pablo",
      "Aldana Pilar",
      "Blanco Estefany",
      "Blanco Jonaz",
      "Calvo Bertha",
      "Calvo Eulogio",
      "Calvo Ildemar",
      "Calvo Yenith",
      "Carreño Maruja",
      "Flores Viarvys",
      "Gonzalez Luz",
      "Gudiño Javier",
      "Martinez Vasty",
      "Niño Oliva",
      "Ordoñez Carmen",
      "Rojas Agustina",
      "Tabares Claudia",
    ],
  },
  {
    nombre: "GRUPO 6",
    miembros: [
      "Villanueva Arcesio",
      "Castillo Jorge",
      "Alviarez Nadia",
      "Bobadilla Miriam",
      "Casanova Carmen",
      "Castillo Kimberly",
      "Castro Argemiro",
      "Luna Magdalena",
      "Montenegro Miriam",
      "Peinado Solfanis",
      "Pérez Olga",
      "Quintero Clara",
      "Quintero Solveira",
      "Quintero William",
      "Torrez Amanda",
      "Villanueva Nereida",
      "Zapata Zulmy",
    ],
  },
  {
    nombre: "GRUPO 7",
    miembros: [
      "Rivero Wilmer",
      "Sierra Jairo",
      "Arias Emerenciana",
      "Arias Maria",
      "Caballero Mariela",
      "Carvajal Olivia",
      "Coronado Fanny",
      "Garcia Jane",
      "Granados Elvia",
      "Graterol Amarilis",
      "Graterol José",
      "Navajas Xiomara",
      "Pinzon Angelys",
      "Rivero Jairenys",
      "Valcarcel Natalia",
      "Valcarcel Rosa",
      "Zumarraga Florentino",
    ],
  },
  {
    nombre: "GRUPO 8",
    miembros: [
      "Trejo Henry",
      "Balaguera Aldemar",
      "Blanco Paola",
      "Blanco Raquel",
      "Blanco Rosa",
      "Colmenares Gloria",
      "Kuicas Aura",
      "León Dominga",
      "León José",
      "León María",
      "López Carolina",
      "López Elda",
      "López Lorena",
      "Parra Daniel",
      "Parra Eglis",
      "Sanabria Ana",
      "Sanabria Anaclovis",
      "Trejo Maryury",
    ],
  },
  {
    nombre: "HNOS. INACTIVOS",
    miembros: [
      "Cordero Aura",
      "Hernández Jhoinner",
      "Kuikas Maria",
      "Lopez Erika",
      "Mendes Maikol",
      "Perez Claudia",
      "Quintero Edwin",
      "Rivera Juan Pablo",
      "Vargas Gabriel",
      "Vargas Janeth",
      "Guarín Yeleiny",
      "Rojas Belsy",
      "Laguado Carolina",
    ],
  },
];
