export const varones = [
  {
    tipo: "Anciano",
    miembros: [
      "Barrera Alvaro",
      "Godoy Juan",
      "Castillo Jorge",
      "Villanueva Arcesio",
      "Rivero Wilmer",
      "Delgado Adrian",
      "Gonzáles Moises",
      "Flórez Juan",
      "Menjura Juan",
      "Murillo Loncio",
      "Sierra Jairo",
    ],
  },
  {
    tipo: "Ministrial",
    miembros: [
      "Trejo Henry",
      "Perez Alexander",
      "Rivera David",
      "Rivera Ciro",
      "Rojas Richard",
      "Graterol Jeremías",
      "Graterol José",
      "Hernández Edgar",
      "Sabas Mauricio",
      "Hernández Harol",
    ],
  },
  {
    tipo: "Varones",
    miembros: [
      "Aldana Pablo",
      "Balaguera Aldemar",
      "Barreto Joel",
      "Blanco Jonas",
      "Bolaños Andi",
      "Boorques Ronny",
      "Calvo Eulogio",
      "Castro Argemiro",
      "Correa Pedro",
      "Gomes Antonio",
      "Gudiño Javier",
      "Leon Jose",
      "Lopez Antonio",
      "Luna Jesus",
      "Parra Daniel",
      "Quintero William",
      "Rangel José",
      "Rojas Jeison",
      "Valdez Alirio",
      "Zerpa Martín",
    ],
  },
];
